#!/bin/bash

echo "=== GraphRAG项目推送到GitHub指南 ==="
echo ""
echo "我们已经提交了以下中文分析文档："
echo "- README_CN.md - 中文版项目介绍"
echo "- 项目代码框架分析.md - 详细的代码架构分析"
echo "- 项目配置指南.md - 完整的安装配置指南"
echo "- GraphRAG业务分析报告.md - 业务角度的项目分析"
echo "- GraphRAG金融科技应用分析.md - 金融领域应用分析"
echo ""
echo "现在需要推送到GitHub。请选择一种方式："
echo ""
echo "方式1: 使用个人访问令牌（推荐，最简单）"
echo "1. 访问 https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. 勾选 'repo' 权限"
echo "4. 复制生成的令牌"
echo "5. 运行以下命令（将 YOUR_TOKEN 替换为实际令牌）："
echo "   git push https://Mikann-Ju:YOUR_TOKEN@github.com/Mikann-Ju/graphrag.git main"
echo ""
echo "方式2: 使用SSH密钥（更安全）"
echo "1. 复制以下公钥："
cat ~/.ssh/id_ed25519.pub
echo ""
echo "2. 访问 https://github.com/settings/keys"
echo "3. 点击 'New SSH key' 并粘贴公钥"
echo "4. 然后运行: git push origin main"
echo ""
echo "如果您已经设置了认证，直接运行: git push origin main" 